"""Initial schema: users, sessions, teacher_enrollments.

Hand-written rather than autogenerated — this sandbox has no Postgres
to run `alembic revision --autogenerate` against (see
ai/finetuning/README.md-style caveat: written to spec, verified by
.github/workflows/ci.yml's postgres service container on push, not
locally this session). Matches backend/models/{session,teacher,user}.py
exactly as of this revision.

Revision ID: 0001
Revises:
Create Date: 2026-08-31
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("owner_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("consent_confirmed", sa.Boolean(), nullable=False),
        sa.Column("chunk_results", sa.JSON(), nullable=False),
        sa.Column("pipeline_options", sa.JSON(), nullable=False),
        sa.Column("transcript_text", sa.String(), nullable=False),
        sa.Column("transcript_segments", sa.JSON(), nullable=False),
        sa.Column("speaker_segments", sa.JSON(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("minutes", sa.JSON(), nullable=True),
        sa.Column("stage_latencies", sa.JSON(), nullable=False),
    )
    op.create_index("ix_sessions_owner_id", "sessions", ["owner_id"])
    op.create_index("ix_sessions_created_at", "sessions", ["created_at"])

    op.create_table(
        "teacher_enrollments",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("owner_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_detail", sa.String(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
    )
    op.create_index("ix_teacher_enrollments_owner_id", "teacher_enrollments", ["owner_id"])


def downgrade() -> None:
    op.drop_index("ix_teacher_enrollments_owner_id", table_name="teacher_enrollments")
    op.drop_table("teacher_enrollments")

    op.drop_index("ix_sessions_created_at", table_name="sessions")
    op.drop_index("ix_sessions_owner_id", table_name="sessions")
    op.drop_table("sessions")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
